export enum IdDocSetType {
  IDENTITY = 'IDENTITY',

  SELFIE = 'SELFIE',

  PROOF_OF_RESIDENCE = 'PROOF_OF_RESIDENCE',

  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',

  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
}
